# Generated by Django 4.2.30 on 2026-05-26 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(choices=[('approve', 'Approved'), ('flag', 'Flagged for Review'), ('edit', 'Value Edited'), ('revert', 'Edit Reverted'), ('upload', 'File Uploaded'), ('reprocess', 'Job Reprocessed')], max_length=20)),
                ('before_value', models.JSONField(blank=True, null=True)),
                ('after_value', models.JSONField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('flight', 'Business Travel — Air'), ('hotel', 'Hotel Stay'), ('fuel', 'Fuel Combustion'), ('electricity', 'Electricity (Grid)'), ('ground', 'Ground Transport')], max_length=20)),
                ('category', models.CharField(max_length=50)),
                ('sub_category', models.CharField(blank=True, default='', max_length=50)),
                ('unit', models.CharField(max_length=50)),
                ('factor_value', models.DecimalField(decimal_places=9, max_digits=18)),
                ('year', models.IntegerField()),
                ('source', models.CharField(max_length=200)),
                ('source_url', models.URLField(blank=True)),
                ('source_sheet', models.CharField(blank=True, max_length=100)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('sap_mm', 'SAP MM (MB51)'), ('utility_hh', 'Utility HH Meter'), ('travel_navan', 'Navan Travel CSV')], max_length=20)),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed'), ('partial', 'Partial (with errors)')], default='pending', max_length=20)),
                ('row_count_total', models.IntegerField(blank=True, null=True)),
                ('row_count_success', models.IntegerField(blank=True, null=True)),
                ('row_count_error', models.IntegerField(blank=True, null=True)),
                ('error_detail', models.JSONField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingestion_jobs', to='breathe_esg.client')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingestion_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmissionRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('sap_mm', 'SAP MM (MB51)'), ('utility_hh', 'Utility HH Meter'), ('travel_navan', 'Navan Travel CSV')], max_length=20)),
                ('source_raw', models.JSONField()),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('activity_date', models.DateField()),
                ('raw_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('raw_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('scope', models.CharField(blank=True, choices=[('1', 'Scope 1 — Direct'), ('2', 'Scope 2 — Electricity'), ('3', 'Scope 3 — Value Chain')], max_length=1, null=True)),
                ('normalized_kgco2e', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('plant_code', models.CharField(blank=True, max_length=4, null=True)),
                ('company_code', models.CharField(blank=True, max_length=4, null=True)),
                ('material_code', models.CharField(blank=True, max_length=40, null=True)),
                ('movement_type', models.CharField(blank=True, max_length=3, null=True)),
                ('cost_centre', models.CharField(blank=True, max_length=10, null=True)),
                ('mpan', models.CharField(blank=True, max_length=13, null=True)),
                ('meter_serial', models.CharField(blank=True, max_length=20, null=True)),
                ('has_estimated_periods', models.BooleanField(blank=True, null=True)),
                ('travel_category', models.CharField(blank=True, max_length=20, null=True)),
                ('origin_iata', models.CharField(blank=True, max_length=3, null=True)),
                ('destination_iata', models.CharField(blank=True, max_length=3, null=True)),
                ('cabin_class', models.CharField(blank=True, max_length=20, null=True)),
                ('carrier_code', models.CharField(blank=True, max_length=2, null=True)),
                ('hotel_country', models.CharField(blank=True, max_length=2, null=True)),
                ('nights', models.IntegerField(blank=True, null=True)),
                ('inferred_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('booking_id', models.CharField(blank=True, max_length=30, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=20, null=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flag_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_rows', to=settings.AUTH_USER_MODEL)),
                ('emission_factor_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emission_rows', to='breathe_esg.emissionfactor')),
                ('ingestion_job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emission_rows', to='breathe_esg.ingestionjob')),
            ],
        ),
        migrations.AddIndex(
            model_name='emissionfactor',
            index=models.Index(fields=['source_type', 'category', 'sub_category', 'valid_from'], name='breathe_esg_source__c9a127_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emissionfactor',
            unique_together={('source_type', 'category', 'sub_category', 'valid_from')},
        ),
        migrations.AddField(
            model_name='auditlog',
            name='emission_row',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='breathe_esg.emissionrow'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='ingestion_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='breathe_esg.ingestionjob'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='emissionrow',
            index=models.Index(fields=['source_type', 'activity_date'], name='breathe_esg_source__2ffcdb_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrow',
            index=models.Index(fields=['ingestion_job'], name='breathe_esg_ingesti_e6a9e0_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrow',
            index=models.Index(fields=['mpan', 'activity_date'], name='breathe_esg_mpan_a1fcd6_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrow',
            index=models.Index(fields=['idempotency_key'], name='breathe_esg_idempot_ed87af_idx'),
        ),
    ]
